language: node_js
node_js:
- '12'
install:
- npm install
- npm run build
after_install:
- ls -l
- cd ..
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  target_branch: gh-pages
  local_dir: docs
  on:
    branch: master
env:
  global:
    secure: 6md0N+WXxGLXuAoBXF5e21qnTr0nYFRG51RFd+KUPrdeNpdGZzTwLS8qkXGvn6BVrcpSzmETtKHPDy1CwDcbMQuyz1nMtJ+LX8cnJSsYW02jpabsH4FDKoUhvS/06kzZXl4Xy3PILdsTWCOCAkVGWwHZCceM3IPzd5GL4N7rOwf9i62nklWBHrTd19JMNYVM9uJXHJoXnGl8noUcT3qj4S15dUsGwSjQgMGzDEECRNphEnd6JtqBw/3fMQztnUMczGK09uwY2yt2nmnrq3scZcodU9hlXWPnRfCRN1Azq/d8BPv5qyC564MQr0DgQQx3/MtGI4Ad/QW2N3S8ncZUx5VPczvYx+M4ZWrSunzG1gjV0LnlXxB5zQk31kyR90lwDP8ju1uf90Cgk3Nr7JooHB9Zi4B6oRg1CCmWwWTKQ7uAIPzUKe+ZybZV1uELBvV0OKOYKnB7LLivXlj+KEQXBfiP/4X84gikA1gbl5gW/AC8u/rH7DOgisyQGerPM1hFYCaE/lxcdT7FRM8u5RzcZfUwfiXmft3vTj8CHywEmD4fFEyMoZz6elJdoB1VDJmzoejlnnaYIJtVCPsn8EJxwysNBOI+81aMFdM8gx45UbJcDPmLzp7y8ivkvZyO0h/sB/IXvQTFWT9P7BofT6/idKAVdnHt+J/wbeP7AfCzUXo=
